-- ============================================================
-- NOVASHOP E-COMMERCE DATABASE
-- ============================================================

create extension if not exists "pgcrypto";


-- ============================================================
-- PRODUCTS
-- ============================================================

create table if not exists public.products (
    id text primary key,
    name text not null,
    description text default '',
    price numeric(12,2) not null check (price >= 0),
    image_url text default '',
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- ORDERS
-- ============================================================

create table if not exists public.orders (
    id uuid primary key,
    user_id uuid not null references auth.users(id) on delete cascade,

    customer_name text not null,
    phone text not null,
    address text not null,
    country text not null,
    state text not null,
    customer_email text,

    payment_method text not null
        check (
            payment_method in (
                'Bank Transfer',
                'Gift Card'
            )
        ),

    payment_proof_path text,

    total_amount numeric(12,2) not null
        check (total_amount >= 0),

    status text not null default 'Received'
        check (
            status in (
                'Received',
                'Payment Under Review',
                'Payment Confirmed',
                'Processing',
                'Completed',
                'Cancelled'
            )
        ),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- ORDER ITEMS
-- ============================================================

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,

    order_id uuid not null
        references public.orders(id)
        on delete cascade,

    product_id text not null,

    product_name text not null,

    unit_price numeric(12,2) not null
        check (unit_price >= 0),

    quantity integer not null
        check (quantity > 0),

    subtotal numeric(12,2) not null
        check (subtotal >= 0),

    created_at timestamptz not null default now()
);


-- ============================================================
-- STORE CONFIGURATION
-- ============================================================

create table if not exists public.store_config (
    id integer primary key default 1
        check (id = 1),

    bank_name text default '',
    account_name text default '',
    account_number text default '',
    bank_instructions text default '',
    gift_card_instructions text default '',

    updated_at timestamptz not null default now()
);


-- ============================================================
-- DEFAULT PAYMENT CONFIG
-- ============================================================

insert into public.store_config (
    id,
    bank_name,
    account_name,
    account_number,
    bank_instructions,
    gift_card_instructions
)
values (
    1,
    'YOUR BANK',
    'YOUR ACCOUNT NAME',
    'YOUR ACCOUNT NUMBER',
    'Transfer the exact order amount and upload your payment proof.',
    'Follow the store owner''s gift-card instructions and upload proof.'
)
on conflict (id) do nothing;


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists idx_orders_user_id
on public.orders(user_id);

create index if not exists idx_orders_created_at
on public.orders(created_at desc);

create index if not exists idx_order_items_order_id
on public.order_items(order_id);

create index if not exists idx_products_active
on public.products(is_active);


-- ============================================================
-- ENABLE RLS
-- ============================================================

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_config enable row level security;


-- ============================================================
-- PRODUCTS POLICIES
-- ============================================================

drop policy if exists "Anyone can read active products"
on public.products;

create policy "Anyone can read active products"
on public.products
for select
to anon, authenticated
using (is_active = true);


-- Customer clients cannot insert/update/delete products.
-- Admin operations use the server-side service role.


-- ============================================================
-- ORDERS POLICIES
-- ============================================================

drop policy if exists "Users can create their own orders"
on public.orders;

create policy "Users can create their own orders"
on public.orders
for insert
to authenticated
with check (
    auth.uid() = user_id
);


drop policy if exists "Users can view their own orders"
on public.orders;

create policy "Users can view their own orders"
on public.orders
for select
to authenticated
using (
    auth.uid() = user_id
);


-- No customer update/delete policy.
-- This prevents customers from changing order status
-- or changing another customer's information.


-- ============================================================
-- ORDER ITEMS POLICIES
-- ============================================================

drop policy if exists "Users can create items for their own orders"
on public.order_items;

create policy "Users can create items for their own orders"
on public.order_items
for insert
to authenticated
with check (
    exists (
        select 1
        from public.orders
        where orders.id = order_items.order_id
        and orders.user_id = auth.uid()
    )
);


drop policy if exists "Users can view items from their own orders"
on public.order_items;

create policy "Users can view items from their own orders"
on public.order_items
for select
to authenticated
using (
    exists (
        select 1
        from public.orders
        where orders.id = order_items.order_id
        and orders.user_id = auth.uid()
    )
);


-- ============================================================
-- STORE CONFIG POLICIES
-- ============================================================

drop policy if exists "Authenticated users can read store config"
on public.store_config;

create policy "Authenticated users can read store config"
on public.store_config
for select
to authenticated
using (true);


-- Only service-role/admin server operations modify this table.


-- ============================================================
-- STORAGE BUCKETS
-- ============================================================

insert into storage.buckets (
    id,
    name,
    public
)
values (
    'payment-proofs',
    'payment-proofs',
    false
)
on conflict (id) do update
set public = false;


insert into storage.buckets (
    id,
    name,
    public
)
values (
    'product-images',
    'product-images',
    true
)
on conflict (id) do update
set public = true;


-- ============================================================
-- PAYMENT PROOF STORAGE POLICIES
-- ============================================================

drop policy if exists "Users can upload their own payment proofs"
on storage.objects;

create policy "Users can upload their own payment proofs"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
);


drop policy if exists "Users can view their own payment proofs"
on storage.objects;

create policy "Users can view their own payment proofs"
on storage.objects
for select
to authenticated
using (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
);


-- The owner uses the service role server-side to access
-- payment proofs. Service role bypasses RLS.


-- ============================================================
-- PRODUCT IMAGE STORAGE POLICIES
-- ============================================================

drop policy if exists "Anyone can view product images"
on storage.objects;

create policy "Anyone can view product images"
on storage.objects
for select
to anon, authenticated
using (
    bucket_id = 'product-images'
);


-- Product image uploads are performed server-side by the
-- authenticated admin using the service-role client.


-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


drop trigger if exists products_updated_at
on public.products;

create trigger products_updated_at
before update on public.products
for each row
execute function public.update_updated_at_column();


drop trigger if exists orders_updated_at
on public.orders;

create trigger orders_updated_at
before update on public.orders
for each row
execute function public.update_updated_at_column();


drop trigger if exists store_config_updated_at
on public.store_config;

create trigger store_config_updated_at
before update on public.store_config
for each row
execute function public.update_updated_at_column();


-- ============================================================
-- GRANTS
-- ============================================================

grant select
on public.products
to anon, authenticated;

grant select, insert
on public.orders
to authenticated;

grant select, insert
on public.order_items
to authenticated;

grant select
on public.store_config
to authenticated;