SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL"
SUPABASE_KEY = "YOUR_SUPABASE_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY = "YOUR_SUPABASE_SERVICE_ROLE_KEY"


APP_URL = "http://localhost:8501"

ADMIN_EMAIL = "YOUR_OWNER_EMAIL"

PAYMENT_PROOF_BUCKET = "payment-proofs"
PRODUCT_IMAGE_BUCKET = "product-images"